name: CD

on:
  push:
    tags:
    - '*'

jobs:
  CD:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install the iOS workload
      run: dotnet workload install ios --ignore-failed-sources

    - name: Build device version
      working-directory: BSImagePicker
      run: xcodebuild -sdk iphoneos -project "BSImagePicker.xcodeproj" -configuration Release

    - name: Build simulator version
      working-directory: BSImagePicker
      run: xcodebuild -sdk iphonesimulator -project "BSImagePicker.xcodeproj" -configuration Release

    - name: Copy one of the frameworks as an initial version of the final output
      working-directory: BSImagePicker
      run: cp -R "build/Release-iphoneos" "build/Release-fat"

    - name: Combine module from another build
      working-directory: BSImagePicker
      run: cp -R "build/Release-iphonesimulator/BSImagePicker.framework/Modules/BSImagePicker.swiftmodule/" "build/Release-fat/BSImagePicker.framework/Modules/BSImagePicker.swiftmodule/"

    - name: Combine iphoneos + iphonesimulator configuration
      working-directory: BSImagePicker
      run: lipo -create -output "build/Release-fat/BSImagePicker.framework/BSImagePicker" "build/Release-iphoneos/BSImagePicker.framework/BSImagePicker" "build/Release-iphonesimulator/BSImagePicker.framework/BSImagePicker"

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: MSBuild /t:SByteDev_Xamarin_iOS_BSImagePicker /p:Configuration=Release /p:Platform=iPhone
      
    - name: Pack
      run: nuget pack Package.nuspec
      
    - name: Upload to NuGet
      run: dotnet nuget push *.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
    
    - name: Create GitHub Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        draft: false
