name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  CI:

    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
      
    - name: Build device version
      working-directory: BSImagePicker
      run: xcodebuild -sdk iphoneos -project "BSImagePicker.xcodeproj" -configuration Release

    - name: Build simulator version
      working-directory: BSImagePicker
      run: xcodebuild -sdk iphonesimulator -project "BSImagePicker.xcodeproj" -configuration Release

    - name: Copy one of the frameworks as an initial version of the final output
      working-directory: BSImagePicker
      run: cp -R "build/Release-iphoneos" "build/Release-fat"

    - name: Combine module from another build
      working-directory: BSImagePicker
      run: cp -R "build/Release-iphonesimulator/BSImagePicker.framework/Modules/BSImagePicker.swiftmodule/" "build/Release-fat/BSImagePicker.framework/Modules/BSImagePicker.swiftmodule/"

    - name: Combine iphoneos + iphonesimulator configuration
      working-directory: BSImagePicker
      run: lipo -create -output "build/Release-fat/BSImagePicker.framework/BSImagePicker" "build/Release-iphoneos/BSImagePicker.framework/BSImagePicker" "build/Release-iphonesimulator/BSImagePicker.framework/BSImagePicker"

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: MSBuild /t:SByteDev_Xamarin_iOS_BSImagePicker /p:Configuration=Release /p:Platform=iPhone
